project:
  type: website
  output-dir: docs

website:
  description: "A blog about statistics, machine learning, and data analysis software"
  site-url: https://josh-tomiyama.github.io/shakastats/ # you must change this appropriately for RSS feeds to work properly
  title: "ShakaStats"
  search: 
    location: navbar
    type: overlay
  navbar:
    right:
      - text: "About"
        href: "./about/about.qmd"
      - text: "Projects"
        href: "./projects/project_listing.qmd"
      - text: "Blog" 
        href: "./blog/blog_listing.qmd"
      - icon: github
        menu:
          - text: Source Code
            href: https://github.com/josh-tomiyama/shakastats
          - text: Report a Bug
            href: https://github.com/josh-tomiyama/shakastats/issues
  cookie-consent:
    type: express
    style: headline
    palette: dark
  page-footer: 
    center: "&copy; 2026, Joshua-Michael Tomiyama" 
    
format:
  html:
    theme:
      dark: darkly
      light: flatly
    respect-user-color-scheme: true
    css: styles.css

editor: visual

